/**
 * @description Integration Handler  Bean for bcmssavecase
 * @author Jaco de Lange
 * @created 2021-03-26
 */
public class CAFUpdateCase_Resp_IB_v1 extends Base_IB{   
    public SaveCaseResponse SaveCaseResponse;
 /**
 * @description Integration Handler  Bean for bcmssavecase
 * @author Jaco de Lange
 * @created 2021-03-26
 */
    public class SaveCaseResponse {
        public String updated;
    }
}