/**
 * @description       : CreateRetailAccountCommon : for Account Create and Link in retail flow
 * @author            : Brian Maswanganyi
**/
public class CreateRetailAccountCommon {
    public string managerNumber;
    public string mandateNumber; 
    public string accountName;
    public string openingReason;
    public string sourceOfFunds;
    public string productFamily;
    public boolean usePackageAccount;
    public string paymentPlanId;
    public string riskRating; 
    public string fraudIndicator;
    public string fraudStatus;
    public string applicationNumber;
    public string spouseAccountNumber;
    public string groupSchemeEmployer;
}