/**
 * @description       :This file needs to be deleted
 * @author            : robertml@absa.africa
 * @last modified on  : 2021-06-03
 * @last modified by  : robertml@absa.africa
 * Modifications Log
 * Ver   Date         Author                 Modification
 * 1.0   2021-06-03   robertml@absa.africa   Initial Version
 **/

public class SendEmailForStatementClass {
	/**
	 * @description
	 * @author robertml@absa.africa | 2021-06-03
	 **/
	public static void sendEmailForStatementDelete() {
		System.debug('The file needs to be deleted');
	}
}