/**
 * @description       : This file needs to be deleted (File needs to be removed from prod)
 * @author            : PaulJohn.duRand@absa.africa
 * @last modified on  : 2021-09-08
 * @last modified by  : PaulJohn.duRand@absa.africa
 **/
@isTest
public class Wqgetanalystcommentsv7RespIBv2Test {
	@isTest
	public static void test() {
		System.assertEquals('Delete', 'Delete', 'Test file is deprecated');
	}
}